### ISSUE TITLE
Differences to birdnetlib

### ISSUE THREAD

**Issue by phibos** [birdnet-team/birdnet#1]
Hello,

thanks for sharing the project with the community. I have been using the Birdnet-Analyzer and the [birdnetlib](https://github.com/joeweiss/birdnetlib) so far. I was wondering why you have implemented a new Python package and did not improve the existing one. What are your plans for the future and why should one change to this project?

**Comment by kahst** [comment]
To be honest, we just wanted to start with a package that we could potentially use to build internal projects. So there is no particular advantage to using our package over `birdnetlib`. At the moment, our package only has very basic functionality and we will probably keep it that way, apart from some additions that our collaborators might ask for. We appreciate the effort the community has put into `birdnetlib` and we will continue to provide the interfaces and support needed for all the great community projects. Maintaining our own package gives us a little more control over the functionality and interfaces, but that's about it. Let us know if there's anything you think we can improve.
